apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
    path: script/helm/garage
    targetRevision: main
    helm:
      valuesObject:
        garage:
          singleNode: true
        deployment:
          replicaCount: 1
        persistence:
          meta:
            size: 100Mi
          data:
            size: 50Gi
        nodeSelector:
          kubernetes.io/hostname: arch-mini
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
