apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/mlflow/charts
    chart: mlflow
    targetRevision: 0.1.0
    helm:
      valuesObject:
        mlflow:
          backendStoreUri: "sqlite:////mlflow/mlflow.db"
          artifactsDestination: "s3://llm-platform/mlflow"
        server:
          flag_options:
            - serve_artifacts
        storage:
          enabled: true
          size: 10Gi
        env:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://garage.garage.svc.cluster.local:3900"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: garage-credentials
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: garage-credentials
                key: secret-access-key
        nodeSelector:
          kubernetes.io/hostname: arch-mini
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
